-- Create team table
CREATE TABLE IF NOT EXISTS public.team (
    id bigint generated by default as identity primary key,
    name text not null,
    role text not null,
    image text,
    sort_order integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for team
ALTER TABLE public.team ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public team are viewable by everyone" ON public.team FOR SELECT USING (true);
CREATE POLICY "Admins/editors can modify team" ON public.team FOR ALL USING (is_editor_or_admin());

-- Create testimonials table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id bigint generated by default as identity primary key,
    name text not null,
    username text,
    body text not null,
    image text,
    rating integer default 5,
    enabled boolean default true,
    sort_order integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()),
    updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for testimonials
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public testimonials are viewable by everyone" ON public.testimonials FOR SELECT USING (true);
CREATE POLICY "Admins/editors can modify testimonials" ON public.testimonials FOR ALL USING (is_editor_or_admin());

